services:
  search_engine:
    container_name: search_engine
    image: elasticsearch:8.18.2
    environment : 
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
    mem_limit: "2G"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - search-network

  kibana:
    container_name: search_engine_dashboard
    image: docker.elastic.co/kibana/kibana:8.18.2
    ports:
      - "5601:5601"
    # environment:
    #   - ELASTICSEARCH_HOSTS=http://search_engine:9200
    depends_on:
      - search_engine
    networks:
      - search-network
networks:
  search-network:
    driver: bridge

volumes:
  esdata: